name: Run tests and linters

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VENV: .venv
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python {{ cookiecutter.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: {{ cookiecutter.python_version }}
    - name: Install dependencies
      run: | 
        make init
        make install
    - name: Lint
      run: make lint
    - name: run tests
      run: make tests
